src/Entity/Contact.php
<?php

namespace App\Entity;

use App\Repository\ContactRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ContactRepository::class)]
class Contact
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 100)]
    private ?string $name = null;

    #[ORM\Column(length: 100)]
    private ?string $email = null;

    #[ORM\Column(length: 100, nullable: true)]
    private ?string $contact_perso = null;

    #[ORM\Column(length: 100, nullable: true)]
    private ?string $contact_pro = null;

    #[ORM\Column(length: 100)]
    private ?string $organisation = null;

    #[ORM\Column(length: 100)]
    private ?string $function = null;

    #[ORM\ManyToOne(targetEntity: self::class, inversedBy: 'contacts')]
    private ?self $parent = null;
    /**
     * @var Collection<int, self>
     */
    #[ORM\OneToMany(targetEntity: self::class, mappedBy: 'parent')]
    private Collection $contacts;

    #[ORM\OneToOne(inversedBy: 'contact')]
    private ?User $user = null;

    /**
     * @var Collection<int, ContactGroup>
     */
    #[ORM\ManyToMany(targetEntity: ContactGroup::class, mappedBy: 'contacts')]
    private Collection $contactGroups;

    /**
     * @var Collection<int, Tender>
     */
    #[ORM\OneToMany(targetEntity: Tender::class, mappedBy: 'contact')]
    private Collection $tender;

    public function __construct()
    {
        $this->contacts = new ArrayCollection();
        $this->contactGroups = new ArrayCollection();
        $this->tender = new ArrayCollection();
    }

 
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    public function getContactPerso(): ?string
    {
        return $this->contact_perso;
    }

    public function setContactPerso(?string $contact_perso): static
    {
        $this->contact_perso = $contact_perso;

        return $this;
    }

    public function getContactPro(): ?string
    {
        return $this->contact_pro;
    }

    public function setContactPro(?string $contact_pro): static
    {
        $this->contact_pro = $contact_pro;

        return $this;
    }

    public function getOrganisation(): ?string
    {
        return $this->organisation;
    }

    public function setOrganisation(string $organisation): static
    {
        $this->organisation = $organisation;

        return $this;
    }

    public function getFunction(): ?string
    {
        return $this->function;
    }

    public function setFunction(string $function): static
    {
        $this->function = $function;

        return $this;
    }

    public function getParent(): ?self
    {
        return $this->parent;
    }

    public function setParent(?self $parent): static
    {
        $this->parent = $parent;

        return $this;
    }

    /**
     * @return Collection<int, self>
     */
    public function getContacts(): Collection
    {
        return $this->contacts;
    }

    public function addContact(self $contact): static
    {
        if (!$this->contacts->contains($contact)) {
            $this->contacts->add($contact);
            $contact->setParent($this);
        }

        return $this;
    }

    public function removeContact(self $contact): static
    {
        if ($this->contacts->removeElement($contact)) {
            if ($contact->getParent() === $this) {
                $contact->setParent(null);
            }
        }

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection<int, ContactGroup>
     */
    public function getContactGroups(): Collection
    {
        return $this->contactGroups;
    }

    public function addContactGroup(ContactGroup $contactGroup): static
    {
        if (!$this->contactGroups->contains($contactGroup)) {
            $this->contactGroups->add($contactGroup);
            $contactGroup->addContact($this);
        }

        return $this;
    }

    public function removeContactGroup(ContactGroup $contactGroup): static
    {
        if ($this->contactGroups->removeElement($contactGroup)) {
            $contactGroup->removeContact($this);
        }

        return $this;
    }
    public function __toString(): string
    {
        return $this->email ?? 'N/A'; 
    }

    /**
     * @return Collection<int, Tender>
     */
    public function getTender(): Collection
    {
        return $this->tender;
    }

    public function addTender(Tender $tender): static
    {
        if (!$this->tender->contains($tender)) {
            $this->tender->add($tender);
            $tender->setContact($this);
        }

        return $this;
    }

    
    public function removeTender(Tender $tender): static
    {
        if ($this->tender->removeElement($tender)) {
            if ($tender->getContact() === $this) {
                $tender->setContact(null);
            }
        }

        return $this;
    }
}

src/Entity/Tender.php
<?php

namespace App\Entity;

use App\Repository\TenderRepository;
use DateTime;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Validator\Context\ExecutionContextInterface;

#[ORM\Entity(repositoryClass: TenderRepository::class)]
#[UniqueEntity(fields: ['contract_number'], message: 'Ce référence est déja utilisé.')]
class Tender
{
    const TO_RESUMED = 0;
    const TO_SUBMITED=1;
    const SUBMITED=2;
    const LOST=3;
    const WON=4;

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $title = "";

    #[ORM\Column(length: 255, unique:true)]
    private ?string $contract_number = "";

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $description = "";

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $location = "";


    #[ORM\Column]
    private ?float $min_budget = 0;

    #[ORM\Column(nullable: true)]
    private ?float $max_budget = 0;

    #[ORM\Column]
    private ?string $status = "0";

    #[ORM\Column]
    private ?string $tender_type = "0";

    #[ORM\ManyToOne(inversedBy: 'tenders')]
    private ?User $responsable = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $url = "";

    #[ORM\Column(type: 'datetime', options: ['default' => 'CURRENT_TIMESTAMP'])]
    private \DateTime $createdAt;


    /**
     * @var Collection<int, Document>
     */
    #[ORM\OneToMany(targetEntity: Document::class, mappedBy: 'tender', cascade:['persist','remove'])]
    private Collection $documents;


    /**
     * @var Collection<int, File>
     */
    #[ORM\OneToMany(targetEntity: File::class, mappedBy: 'tender', cascade:['persist','remove'])]
    private Collection $files;



    /**
     * @var Collection<int, Calendar>
     */
    #[ORM\OneToMany(targetEntity: Calendar::class, mappedBy: 'tender', cascade:['persist','remove'])]
    private Collection $calendars;


   /**
     * @var Collection<int, Allotissement>
     */
    #[ORM\OneToMany(targetEntity: Allotissement::class, mappedBy: 'tender', cascade:['persist','remove'])]
    private Collection $allotissements;


    #[ORM\Column]
    private ?bool $isArchived = false;

    #[ORM\OneToOne(mappedBy: 'tender', cascade: ['persist', 'remove'])]
    private ?TenderDate $tenderDate = null;

    #[ORM\ManyToOne(inversedBy: 'tender')]
    private ?Contact $contact = null;
    public function __construct()
    {
        $this->documents = new ArrayCollection();
        $this->calendars = new ArrayCollection();
        $this->files = new ArrayCollection();
        $this->createdAt = new \DateTime(); // Mettre la date actuelle par défaut
    }
    public function __toString(): string
    {
        return $this->contract_number ?? 'N/A'; 
    }


    #[Assert\Callback]
    public function validateBudget(ExecutionContextInterface $context): void
    {
        if ($this->min_budget && $this->max_budget && $this->min_budget >= $this->max_budget) {
            $context->buildViolation('La budget min doit être inferieur au budget max.')
                ->atPath('max_budget')
                ->addViolation();
        }
    }



    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getContractNumber(): ?string
    {
        return $this->contract_number;
    }

    public function setContractNumber(string $contract_number): static
    {
        $this->contract_number = $contract_number;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getLocation(): ?string
    {
        return $this->location;
    }

    public function setLocation(?string $location): static
    {
        $this->location = $location;

        return $this;
    }

    public function getMinBudget(): ?float
    {
        return $this->min_budget;
    }

    public function setMinBudget(float $min_budget): static
    {
        $this->min_budget = $min_budget;

        return $this;
    }

    public function getMaxBudget(): ?float
    {
        return $this->max_budget;
    }

    public function setMaxBudget(?float $max_budget): static
    {
        $this->max_budget = $max_budget;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): static
    {
        $this->status = $status;

        return $this;
    }

    public function getTenderType(): ?string
    {
        return $this->tender_type;
    }

    public function setTenderType(string $tender_type): static
    {
        $this->tender_type = $tender_type;

        return $this;
    }

    public function getCreatedAt(): ?\DateTime
    {
        return $this->createdAt;
    }
    public function setCreatedAt(?\DateTime $date): static
    {
        $this->createdAt = $date;

        return $this;
    }
    public function getResponsable(): ?User
    {
        return $this->responsable;
    }

    public function setResponsable(?User $responsable): static
    {
        $this->responsable = $responsable;

        return $this;
    }

    public function getUrl(): ?string
    {
        return $this->url;
    }

    public function setUrl(?string $url): static
    {
        $this->url = $url;

        return $this;
    }
    

     /**
     * @return Collection<int, Document>
     */
    public function getDocuments(): Collection
    {
        return $this->documents;
    }

   

    public function isArchived(): ?bool
    {
        return $this->isArchived;
    }

    public function setIsArchived(bool $isArchived): static
    {
        $this->isArchived = $isArchived;

        return $this;
    }

    public function getTenderDate(): ?TenderDate
    {
        return $this->tenderDate;
    }

    public function setTenderDate(?TenderDate $tenderDate): static
    {
        if ($tenderDate === null && $this->tenderDate !== null) {
            $this->tenderDate->setTender(null);
        }

        if ($tenderDate !== null && $tenderDate->getTender() !== $this) {
            $tenderDate->setTender($this);
        }

        $this->tenderDate = $tenderDate;

        return $this;
    }

    public function getContact(): ?Contact
    {
        return $this->contact;
    }

    public function setContact(?Contact $contact): static
    {
        $this->contact = $contact;

        return $this;
    }

}

src/Entity/TenderDate.php
<?php

namespace App\Entity;

use App\Repository\TenderDateRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Validator\Context\ExecutionContextInterface;

#[ORM\Entity(repositoryClass: TenderDateRepository::class)]
class TenderDate
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $submissionDate = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $responseDate = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $attributionDate = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $negociationDate = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $start_date = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $end_date = null;

    #[ORM\OneToOne(inversedBy: 'tenderDate',cascade: ['persist', 'remove'])]
    private ?Tender $tender = null;


    #[ORM\Column]
    private ?float $duration = 0;

    /**
     * @var Collection<int, Reminder>
     */
    #[ORM\OneToMany(targetEntity: Reminder::class, mappedBy: 'tenderDate', cascade: ['persist','remove'])]
    private Collection $reminder;

    public function __construct()
    {
        $this->reminder = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getSubmissionDate(): ?\DateTimeInterface
    {
        return $this->submissionDate;
    }

    public function setSubmissionDate(?\DateTimeInterface $submissionDate): static
    {
        $this->submissionDate = $submissionDate;

        return $this;
    }

    public function getResponseDate(): ?\DateTimeInterface
    {
        return $this->responseDate;
    }

    public function setResponseDate(?\DateTimeInterface $responseDate): static
    {
        $this->responseDate = $responseDate;

        return $this;
    }

    public function getAttributionDate(): ?\DateTimeInterface
    {
        return $this->attributionDate;
    }

    public function setAttributionDate(?\DateTimeInterface $attributionDate): static
    {
        $this->attributionDate = $attributionDate;

        return $this;
    }

    public function getNegociationDate(): ?\DateTimeInterface
    {
        return $this->negociationDate;
    }

    public function setNegociationDate(?\DateTimeInterface $negociationDate): static
    {
        $this->negociationDate = $negociationDate;

        return $this;
    }

    public function getStartDate(): ?\DateTimeInterface
    {
        return $this->start_date;
    }

    public function setStartDate(?\DateTimeInterface $start_date): static
    {
        $this->start_date = $start_date;

        return $this;
    }

    public function getEndDate(): ?\DateTimeInterface
    {
        return $this->end_date;
    }

    public function setEndDate(?\DateTimeInterface $end_date): static
    {
        $this->end_date = $end_date;

        return $this;
    }

    public function getTender(): ?Tender
    {
        return $this->tender;
    }

    public function setTender(?Tender $tender): static
    {
        $this->tender = $tender;

        return $this;
    }


    public function getDuration(): ?float
    {
        return $this->duration;
    }

    public function setDuration(float $duration): static
    {
        $this->duration = $duration;

        return $this;
    }
    public function __toString(): string
    {
        return $this->id; 
    }

    /**
     * @return Collection<int, Reminder>
     */
    public function getReminder(): Collection
    {
        return $this->reminder;
    }

    public function addReminder(Reminder $reminder): static
    {
        if (!$this->reminder->contains($reminder)) {
            $this->reminder->add($reminder);
            $reminder->setTenderDate($this);
        }

        return $this;
    }

    public function removeReminder(Reminder $reminder): static
    {
        if ($this->reminder->removeElement($reminder)) {
            if ($reminder->getTenderDate() === $this) {
                $reminder->setTenderDate(null);
            }
        }

        return $this;
    }
}

templates/tender/sections/allotissement_section.html.twig
 <div class="px-4 my-3">
    <div class="row">
        <div class="clearfix ">
            <p class="float-start fs-4">Listes des allotissements</p> 
            <a href="#" class="btn btn-primary float-end" data-bs-toggle="modal" data-bs-target="#addAllotissementModal"> Ajouter un allotissement</a>     
        </div>  
        <table class="table table-borderless">
            <thead>
                <tr>
                    <th>Numéro</th>
                    <th>Titre</th>
                    <th>Description</th>
                    <th>Budget minimum</th>
                    <th>Budget maximum</th>
                </tr>
            </thead>
            <tbody>
                {% for allotissement in allotissements %}
                    <tr>
                        <td><a href="{{ path('app_allotissement_show', {'id': allotissement.id}) }}">{{ allotissement.number }}</a></td>
                        <td>{{ allotissement.title }}</td>
                        <td>{{ allotissement.description |u.truncate(50, '...') }}</td>
                        <td>{{ allotissement.minBudget }}</td>
                        <td>{{ allotissement.maxBudget }}</td>
                    </tr>
                {% else %}
                    <tr>
                        <td colspan="7">aucun</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

  <div class="modal fade" id="addAllotissementModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="addAllotissementModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h1 class="modal-title fs-5" id="addAllotissementModalLabel">Nouveau</h1>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            {{ form_start(form_allotissement,{'action':path('app_allotissement_new',{'id':tender.id})}) }}
                <div class="modal-body">
                    {{ form_rest(form_allotissement) }}
                </div>
                <div class="modal-footer">
                <button class="btn btn-primary" type="submit">{{ button_label|default('Créer') }}</button>
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fermer</button>
                </div>
            {{ form_end(form_allotissement) }}
            
          </div>
        </div>
</div>

templates/tender/sections/document_section.html.twig
<div class="px-4 my-3">
    <div class="row">
        <div class="clearfix ">
            <p class="float-start fs-4">Listes des documents</p>
            <a href="#" class="btn btn-primary float-end" data-bs-toggle="modal" data-bs-target="#addDocumentModal"> + Ajouter</a>     
        </div>

        {% for status, documents in groupedDocuments %}
              <div class="col p-1">
                  <div class="card border-{{status | getStatusColor}}">
                        <div class="card-header text-{{status | getStatusColor}}">
                        <p class="h4"> {{status | getDocumentStatus}}</p>
                        </div>
                        <div class="list-group" data-controller="sortable" data-sortable-group-value="{{status}}" data-group="{{status}}">
                            {% for document in documents %}
                            
                            <div class="card"  data-id="{{document.id}}">
                                <a href="{{path('app_document_show', {'id':document.id})}}" class="list-group-item list-group-item-action" aria-current="true">
                                {{ document.filename}}  <br/>
                                <small class="fw-medium text-reset">{{ document.name | u.truncate(40, '...')}}</small>
                                <br/>
                                <small class="{{ document.limitDate | highlight}}">Date: {{ document.limitDate ? document.limitDate|date('d F Y') : 'aucun' }}</small>
                                <br/>
                                <small class="float-start">Par: {{document.responsable.email}}</small>

                                </a>
                                <a href="{{path('app_document_edit', {'id':document.id})}}" data-id="{{document.id}}" class="btn text-{{status | getStatusColor}} clearfix" aria-current="true">
                                <span class="float-end">Modifier</span>
                                </a>
                            </div>
                            
                        
                            {% else %}
                            {% endfor %}
                        </div>
                    </div>
                </div>
                 
        {% else %}
            <small>Aucun document.</small>
        {% endfor %}
    </div>
</div>

<div class="modal fade" id="addDocumentModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="addDocumentModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h1 class="modal-title fs-5" id="addDocumentModalLabel">Nouveau</h1>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            {{ form_start(form_document,{'action':path('app_document_new',{'id':tender.id})}) }}

            <div class="modal-body">
            
                    {{ form_errors(form_document) }}
                      {{ form_label(form_document.name) }}
                      {{ form_widget(form_document.name) }}

                    <div class="my-3 row">
                      <div class="col-md-6">
                          {{ form_label(form_document.status) }}
                          {{ form_widget(form_document.status) }}
                      </div>
                      <div class="col-md-6">
                          {{ form_label(form_document.responsable) }}{{ form_widget(form_document.responsable) }}
                      </div>
                    </div>
                    {{ form_rest(form_document) }}

            </div>
            <div class="modal-footer">
              <button class="btn btn-primary" type="submit">{{ button_label|default('Créer') }}</button>
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fermer</button>
            </div>
            {{ form_end(form_document) }}
          </div>
        </div>
      </div>

templates/tender/sections/information_section.html.twig
<div class="row px-4 my-3">
    <p class="fs-4 my-2"> Informations sur l'appel d'offre</p> 
    <div class="col-md-8">
        <dl class="row">
            <dt class="col-sm-4 fw-medium">Réference</dt>
            <dd class="col-sm-8">{{ tender.contractNumber }}</dd>
            <dt class="col-sm-4 fw-medium">Nom du projet</dt>
            <dd class="col-sm-8">{{ tender.title }}.</dd>


            <dt class="col-sm-4 fw-medium">Type du marché</dt>
            <dd class="col-sm-8">{{tender.tenderType | getTenderType}}</dd>
            <dt class="col-sm-4 fw-medium">Adresse</dt>
            <dd class="col-sm-8">{{ tender.location }}</dd>
            <dt class="col-sm-4 fw-medium">Budget minimum</dt>
            <dd class="col-sm-8">{{ tender.minBudget }}.</dd>
            <dt class="col-sm-4 fw-medium">Budget maximum</dt>
            <dd class="col-sm-8">{{ tender.maxBudget }}.</dd>

            <dt class="col-sm-4 fw-medium">Responsable</dt>
            <dd class="col-sm-8">{{ tender.Responsable }}</dd>
            <dt class="col-sm-4 fw-medium"><a href="{{ tender.url }}" class="">Visiter le site </a></dt>
            <dd></dd>


        </dl>
    </div>
    <div class="col-md-4">
        <div class="row">
            <dt class="col-sm-4 fw-medium"> Soumission</dt>
            <dd class="col-sm-8"><p class="p-0 m-0{{ tender_date.submissionDate| highlight }}">{{ tender_date.submissionDate ? tender_date.submissionDate|date('d F Y H:i') : '' }}</p></dd>
            <dt class="col-sm-4 fw-medium"> Négociation</dt>
            <dd class="col-sm-8"><p class="p-0 m-0{{ tender_date.negociationDate| highlight }}">{{ tender_date.negociationDate ? tender_date.negociationDate|date('d F Y H:i') : '' }}</p></dd>
            <dt class="col-sm-4 fw-medium"> Réponse</dt>
            <dd class="col-sm-8"><p class="p-0 m-0{{ tender_date.responseDate| highlight }}">{{ tender_date.responseDate ? tender_date.responseDate|date('d F Y H:i') : '' }}</p></dd>
            <dt class="col-sm-4 fw-medium"> Attribution</dt>
            <dd class="col-sm-8"><p class="p-0 m-0{{ tender_date.attributionDate| highlight }}">{{ tender_date.attributionDate ? tender_date.attributionDate|date('d F Y H:i') : '' }}</p></dd>
            <dt class="col-sm-4 fw-medium"> Début</dt>
            <dd class="col-sm-8"><p class="p-0 m-0{{ tender_date.startDate| highlight }}">{{ tender_date.startDate ? tender_date.startDate|date('d F Y H:i') : '' }}</p></dd>
            <dt class="col-sm-4 fw-medium"> Fin</dt>
            <dd class="col-sm-8"><p class="p-0 m-0{{ tender_date.endDate| highlight }}">{{ tender_date.endDate ? tender_date.endDate|date('d F Y H:i') : '' }}</p></dd>

            <dt class="col-sm-4 fw-medium">Durrée</dt>
            <dd class="col-sm-8">{{ tender_date.duration }} ans</dd>
            <dt class="col-sm-4 fw-medium ">Status</dt>
            <dd class="col-sm-8"><span class="badge bg-{{tender.status | getStatusColor}} fw-bolder">{{tender.status | getTenderStatus}}</span></dd>


        </div>

    </div>
</div>

<div class="px-4 my-3">
    <p class="fs-4 my-2">Description</p> 
    {{ tender.description }}
</div>

<div class="px-4 my-3">
    <p class="fs-4 my-2">Opérations</p> 
    <div class="col-md-8">
        <ol class="list-group">
            <li class="list-group-item d-flex justify-content-between align-items-start">
                <div class="ms-2 me-auto fw-medium">Modifier les informations généraux</div>
                <a href="{{ path('app_tender_edit_informations', {'id': tender.id}) }}" class="btn btn-outline-primary">Modifier</a>
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-start">
                <div class="ms-2 me-auto">
                    <div class="fw-medium"> Modifier les dates</div>
                </div>
                <a href="{{ path('app_tender_edit_date', {'id': tender.id}) }}" class="btn btn-outline-primary">Modifier</a>
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-start">
                <div class="ms-2 me-auto fw-medium">Archiver le projet</div>
                <form method="post" action="{{ path('app_tender_archive', {'id': tender.id}) }}" onsubmit="return confirm('Êtes-vous sûr de vouloir archiver ce projet?');">
                    <input type="hidden" name="_token" value="{{ csrf_token('archive' ~ tender.id) }}">
                    <button class="btn btn-outline-warning">Archiver</button>
                </form>
            </li>

            {% if is_granted('ROLE_ADMIN') %}
            <li class="list-group-item d-flex justify-content-between align-items-start">
                <div class="ms-2 me-auto fw-medium"> Supprimer le projet</div>
                <form method="post" action="{{ path('app_tender_delete', {'id': tender.id}) }}" onsubmit="return confirm('Êtes-vous sûr de vouloir supprimer ce projet?');">
                    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ tender.id) }}">
                    <button class="btn btn-outline-danger">Supprimer</button>
                </form>
            </li>
            {% endif %} 
        </ol>
    </div>
</div>
                   

templates/tender/sections/organisation_section.html.twig
<div class="px-4 my-3">
        <div class="row">
            <p class="fs-4 my-2">Informations sur l'organisation</p> 
            {% if tender.contact %}
            <div class="col row">
                <dt class="col-sm-4">Organisation</dt>
                <dd class="col-sm-8">{{tender.contact.organisation}}</dd>
                <dt class="col-sm-4">Nom</dt>
                <dd class="col-sm-8">{{tender.contact.name}}</dd>
                <dt class="col-sm-4">Poste</dt>
                <dd class="col-sm-8">{{tender.contact.function}}</dd>
                <dt>
                    <a href="{{path('app_tender_edit_organisation',{'id':tender.id})}}" class="btn btn-secondary">Modifier</a>
                </dt>
            </div>
            <div class="col row">
                <dt class="col-sm-4">Email</dt>
                <dd class="col-sm-8">{{ tender.contact.email }}</dd>
                <dt class="col-sm-4">Contact perso</dt>
                <dd class="col-sm-8">{{ tender.contact.contactPerso }}</dd>
                <dt class="col-sm-4">Contact pro</dt>
                <dd class="col-sm-8">{{ tender.contact.contactPro }}</dd>
            </div>
            
            {% else %}
                <div class="col-md-4">
                    <a href="{{path('app_tender_edit_organisation',{'id':tender.id})}}" class="btn btn-primary">Ajouter un nouveau</a>
                </div>
            {% endif %}
        </div>
    </div>

                   