src/Entity/History.php
<?php

namespace App\Entity;

use App\Repository\HistoryRepository;
use DateTime;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: HistoryRepository::class)]
class History
{
    const TENDER_TYPE=0;
    const DOCUMENT_TYPE=1;
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(nullable: true)]
    private ?int $actor_id = null;

    #[ORM\Column(length: 255)]
    private ?string $actions = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, options: ['default' => 'CURRENT_TIMESTAMP'])]
    private ?\DateTimeInterface $date;

    #[ORM\Column]
    private ?int $type = null;

    #[ORM\Column]
    private ?int $type_id = null;

    public function __construct() {
        $this->date=new \DateTime();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getActorId(): ?int
    {
        return $this->actor_id;
    }

    public function setActorId(?int $actor_id): static
    {
        $this->actor_id = $actor_id;

        return $this;
    }

    public function getActions(): ?string
    {
        return $this->actions;
    }

    public function setActions(string $actions): static
    {
        $this->actions = $actions;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): static
    {
        $this->date = $date;

        return $this;
    }

    public function getType(): ?int
    {
        return $this->type;
    }

    public function setType(int $type): static
    {
        $this->type = $type;

        return $this;
    }

    public function getTypeId(): ?int
    {
        return $this->type_id;
    }

    public function setTypeId(int $type_id): static
    {
        $this->type_id = $type_id;

        return $this;
    }
}

templates/components/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-primary">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/components/_notification.html.twig
<ul class="dropdown-menu dropdown-menu-end" aria-labelledby="notificationDropdown" style="min-width: 500px;">
    {% for notification in notifications %}
        <li class="dropdown-item d-flex justify-content-between">
            {% if notification.type == 1 %}
                 <a class="link-offset-2 link-underline link-underline-opacity-0 text-wrap" href="{{ path('app_tender_show', {'id': notification.typeId}) }}">{{ notification.message }}</a>

            {% elseif notification.type == 2 %}
                 <a class="link-offset-2 link-underline link-underline-opacity-0 text-wrap" href="{{ path('app_document_show', {'id': notification.typeId}) }}">{{ notification.message }}</a>

            {% endif %}
            {% if not notification.isRead %}
                <a href="{{ path('notification_mark_read', {'id': notification.id}) }}" class="btn btn-sm"><i class="bi bi-x-lg"></i></a>
            {% endif %}
        </li>
    {% else %}
        <li class="dropdown-item text-muted text-center">Aucune nouvelle notification.</li>
    {% endfor %}
</ul>

templates/components/navbar.html.twig
<div class="col-sm-auto bg-light sticky-top">
    <div class="d-flex flex-sm-column flex-row flex-nowrap bg-light align-items-center sticky-top text-center">
        <a href="{{ path('app_home') }}" class="d-block p-3 link-blue text-decoration-none" title="" data-bs-toggle="tooltip" data-bs-placement="right" data-bs-original-title="Icon-only">
          <i class="bi bi-speedometer2 {% if app.request.get('_route') == 'app_home' %}fs-1 {% else %} fs-2{% endif %}"></i>
                    <small>Dashboard</small>
        </a>
        
        <ul class="nav nav-pills nav-flush flex-sm-column flex-row flex-nowrap mb-auto mx-auto text-center">
            <li>
                <a href="{{ path('app_tender_index') }}" class="nav-link py-3 px-2 "  title="Appels d'offres" data-bs-toggle="tooltip" data-bs-placement="right" data-bs-original-title="Tenders">
                    <i class="bi bi-card-list {% if app.request.get('_route') == 'app_tender_index' %}fs-1 {% else %} fs-3{% endif %}"></i>
                    </br>
                    <small>Tender</small>
                </a>
            </li>

        

            <li>
                <a href="{{ path('app_calendar_index') }}" class="nav-link py-3 px-2" title="Calendrier" data-bs-toggle="tooltip" data-bs-placement="right" data-bs-original-title="Calendars">
                  <i class="bi bi-calendar3 {% if app.request.get('_route') == 'app_calendar_index' %}fs-1 {% else %} fs-3{% endif %}"></i>
                   </br>
                   <small>Calendrier</small>
              </a>
            </li>
               <li>
                <a href="{{ path('app_document_index') }}" class="nav-link py-3 px-2" title="Documents" data-bs-toggle="tooltip" data-bs-placement="right" data-bs-original-title="Documents">
                  <i class="bi bi-folder {% if app.request.get('_route') == 'app_document_index' %}fs-1 {% else %} fs-3{% endif %}"></i>
                    </br>
                    <small>Document</small>
              </a>
            </li>
            <li>
                <a href="{{ path('app_contact_index') }}" class="nav-link py-3 px-2" title="Contacts" data-bs-toggle="tooltip" data-bs-placement="right" data-bs-original-title="Customers">
                    <i class="bi bi-people {% if app.request.get('_route') == 'app_contact_index' %}fs-1 {% else %} fs-3{% endif %}"></i>
                    </br>
                    <small>Contact</small>
                </a>
            </li>
<li>
                <a href="{{ path('app_archive_index') }}" class="nav-link py-3 px-2" title="archives" data-bs-toggle="tooltip" data-bs-placement="right" data-bs-original-title="Customers">
                  <i class="bi bi-archive {% if app.request.get('_route') == 'app_archive_index' %}fs-1 {% else %} fs-3{% endif %}"></i>
                  </br>
                  <small>Archive</small>
                </a>
            </li>
            
        </ul>
        <div class="dropdown">
            <a href="#" class="d-flex align-items-center justify-content-center p-3 link-dark text-decoration-none dropdown-toggle" id="dropdownUser3" data-bs-toggle="dropdown" aria-expanded="false">
                <i class="bi-person-circle h4"></i>
            </a>
            <ul class="dropdown-menu text-small shadow" aria-labelledby="dropdownUser3">
                {% if is_granted('ROLE_ADMIN') %}
                <li><a class="dropdown-item" href="{{ path('admin') }}">Section admin</a></li>
                {% endif %}
                <li><a class="dropdown-item" href="{{ path('app_tender_new') }}">Nouveau tender...</a></li>
               
                <li><a class="dropdown-item" href="{{ path('app_logout') }}">Se deconnecter</a></li>
               
            </ul>
        </div>
    </div>
</div>

templates/components/tender_search_result.html.twig
{% extends 'base.html.twig' %}

{% block title %}Tenders{% endblock %}

{% block body %}
<div class="container-fluid">
    <div class="row mb-5">
            <div class="row">
                <div class="col">
                    <p class="h2 text-{{status | getStatusColor}}">{{status | getTenderStatus}}: ({{tenders | length}})</p>
                </div>            
            </div>

            {{include('tender/_tender_lists.html.twig',{'tenders':tenders})}}
            
    </div>
</div>
{% endblock %}